#include "chemdata.h"

using namespace std;
const vector<float> massData =
        {0, 1.007947, 4.0026022, 6.9412, 9.0121823, 10.8117, 12.01078, 14.00672, 15.99943, 18.99840325, 20.17976,
         22.989769282, 24.30506, 26.98153868, 28.08553, 30.9737622, 32.0655, 35.4532, 39.9481, 39.09831, 40.0784,
         44.9559126, 47.8671, 50.94151, 51.99616, 54.9380455, 55.8452, 58.9331955, 58.69342, 63.5463, 65.394, 69.7231,
         72.641, 74.921602, 78.963, 79.9041, 83.7982, 85.46783, 87.621, 88.905852, 91.2242, 92.906382, 95.942, 97.9072,
         101.072, 102.905502, 106.421, 107.86822, 112.4118, 114.8183, 118.7107, 121.7601, 127.603, 126.904473, 131.2936,
         132.90545192, 137.3277, 137.3277, 140.1161, 140.907652, 144.2423, 145, 150.362, 151.9641, 157.253, 158.925352,
         162.5001, 164.930322, 167.2593, 168.934212, 173.043, 174.9671, 178.492, 180.947882, 183.841, 186.2071, 190.233,
         192.2173, 195.0849, 196.9665694, 200.592, 204.38332, 207.21, 208.980401, 208.9824, 209.9871, 222.0176, 223,
         226, 227, 232.038062, 231.035882, 238.028913, 238.8486, 242.8798, 244.8594, 246.911, 248.9266, 252.9578,
         253.9656, 259.0046, 260.0124, 261.0202, 264.0436, 269.0826, 270.0904, 273.1138, 274.1216, 272.106, 278.1528,
         283.1918, 282.184, 287.223};
const vector<float> electronegativityData =
        {0, 2.20, 3.89, 0.98, 1.57, 2.04, 2.55, 3.04, 3.44, 3.98, 3.67, 0.93, 1.31, 1.61, 1.90, 2.19, 2.58, 3.16, 3.3,
         0.82, 1.00, 1.36, 1.54, 1.63, 1.66, 1.55, 1.83, 1.88, 1.91, 1.90, 1.65, 1.81, 2.01, 2.18, 2.55, 2.96, 3.00,
         0.82, 0.95, 1.22, 1.33, 1.6, 2.16, 1.9, 2.2, 2.28, 2.20, 1.93, 1.69, 1.78, 1.96, 2.05, 2.1, 2.66, 2.67, 0.97,
         0.89, 1.1, 1.12, 1.13, 1.14, 1.13, 1.17, 1.2, 1.2, 1.1, 1.22, 1.23, 1.24, 1.25, 1.1, 1.27, 1.3, 1.5, 2.36, 1.9,
         2.2, 2.20, 2.28, 2.54, 2.00, 1.62, 2.33, 2.02, 2.0, 2.2, 2.2, 0.7, 0.9, 1.1, 1.3, 1.5, 1.38, 1.36, 1.28, 1.13,
         1.28, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.291, 1.3, 1.5, 2.36, 1.9, 2.2, 2.20, 2.28, 2.54, 2.00};
const vector<string> nameData =
        {"None", "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar",
         "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb",
         "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba",
         "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W",
         "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U",
         "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds",
         "Rg", "Cn"};
const vector<string> formulaData =
        {"CCl4", "CH3Cl", "C2H5OC2H5", "KO2", "CuCl2", "CHCl3", "CH3COONa", "CH3COOCH3", "CH3COOC2H5", "CH3CH2Br",
         "CH2Cl2", "C2H5ONa", "(C2H5O)2Mg", "C2H5ONO2", "CH3CH2OSO3H", "(C2H5O)3Al", "CH3CH2OH", "C11H22O11",
         "Ba(NO3)2", "Al2S3", "NaAlO2", "NH3·H2O", "AgOH", "Ca(ClO)2", "Ca(H2PO4)2", "CH4", "C2H6", "C2H4", "C2H2",
         "Fe(NO3)2", "CaC2", "CH3CHO", "C2H5OH", "Fe(OH)2", "Ca(HCO3)2", "CH3OH", "Ag(NH3)2OH", "HCHO", "HClO",
         "K2MnO4", "NaH", "Mg(HCO3)2", "Mg3N2", "MgSiO3", "NO2", "NO", "N2O4", "Na2SO4", "Cu(OH)2", "H4SiO4", "H2SiO3",
         "NaBr", "NaHS", "NaHSO3", "NaHSO4", "Cu3P", "HPO3", "PCl5", "PCl3", "C6H5SO3H", "C6H12", "C6H6", "C6H5Br",
         "C6H5Cl", "CS2", "K2S", "Ca(HSO3)2", "CaSO3", "CaSiO3", "ZrOCl2", "ZrO2", "Zr(SO4)2", "Zr(NO3)4", "Zr",
         "ZnSO4", "ZnS", "ZnO", "ZnCl2", "ZnCO3", "ZnC2O4", "Zn2P2O7", "Zn(NO3)2", "Zn", "WO3", "W", "VO2", "V2O5", "V",
         "UO3", "UF4", "UCl4", "U3O8", "U", "TiOSO4", "TiO2", "TiCl4", "TiCl3", "Ti", "ThCl4", "Th(SO4)2", "Th(NO3)4",
         "Th(C2O4)2", "Th", "SrSO4", "SrO", "SrCl2", "SrCO3", "SrC2O4", "Sr3(PO4)2", "Sr(NO3)2", "Sr", "SnS2", "SnS",
         "SnO2", "SnCl2", "Sn", "SiO2", "SiF4", "SiCl4", "Si", "SbCl5", "SbCl3", "Sb2O5", "Sb2O3", "Sb", "SO3", "SO2",
         "S", "PbbI2", "PbSO4", "PbS", "PbO2", "PbO", "PbCrO4", "PbCl2", "PbCO3", "PbC2O4", "Pb3O4", "Pb3(PO4)2",
         "Pb2O3", "Pb(NO3)2", "Pb(IO3)2", "Pb", "P2O5", "P", "O3", "O2", "O", "NiSO4", "NiS", "NiO", "NiCl2",
         "Ni(NO3)2", "Ni", "NaOH", "NaNO3", "NaNO2", "NaI", "NaHCO3", "NaH2PO4", "NaH", "NaClO", "NaCl", "NaCO3",
         "NaCN", "NaBrO3", "NaBiO3", "NaAsO4", "Na3PO4", "Na3AsO4", "Na3AsO3", "Na2SO4", "Na2SiO3", "Na2SO3", "Na2S2O3",
         "Na2S", "Na2O2", "Na2O", "Na2HPO4", "Na2HAsO3", "Na2CrO4", "Na2CO3", "Na2C2O4", "Na2B4O7", "Na", "NH4VO3",
         "NH4NO3", "NH4HCO3", "NH4H2PO4", "NH4Cl", "NH3", "N2", "N", "MnSO4", "MnS", "MnO2", "MnO", "MnCl2", "MnCO3",
         "Mn3O4", "Mn2P2O7", "Mn2O3", "Mn(NO3)2", "Mn", "MgSO4", "MgO", "MgNH4PO4", "MgNH4AsO4", "MgH2", "MgCl2",
         "MgCO3", "MgC2O4", "Mg2P2O7", "Mg(OH)2", "Mg(NO3)2", "Mg", "LiOH", "LiH", "LiCl", "Li2O", "Li2CO3", "Li",
         "KOH", "KNaC4O6H4", "KNO3", "KNO2", "KMnO4", "KIO3", "KI", "KHSO4", "KHC8O4H8", "KHC4O6H4", "KHC2O4", "KH",
         "KFe(SO4)2", "KF", "KClO4", "KClO3", "KCl", "KBrO3", "KBr", "KAl(SO4)2", "K4Fe(CN)6", "K3PO4", "K3Fe(CN)6",
         "K3AsO4", "K2SO4", "K2S2O7", "K2PtCl6", "K2O", "K2CrO4", "K2Cr2O7", "K2CO3", "K", "I2", "I", "HgSO4", "HgS",
         "HgO", "HgI2", "HgCl2", "Hg2SO4", "Hg2I2", "Hg2Cl2", "Hg2Br2", "Hg2(NO3)2", "Hg(NO3)2", "Hg(CN)2", "Hg",
         "HNO3", "HNO2", "HIO3", "HI", "HF", "HClO4", "HCl", "HCOONa", "HCOOH", "HCN", "HBr", "H3PO4", "H3PO3", "H3BO3",
         "H3AsO4", "H3AsO3", "H2SO4", "H2SO3", "H2S", "H2O2", "H2O", "H2CO3", "H2C2O4", "H2", "H", "FeSO4", "FeS2",
         "FeS", "FeO", "FeCl3", "FeCl2", "FeCO3", "Fe3O4", "Fe2O3", "Fe2(SO4)3", "Fe(OH)3", "Fe(NO3)3", "Fe", "F2", "F",
         "CuSO4", "CuSCN", "CuS", "CuO", "CuCl2CuI", "CuCl", "Cu2S", "Cu2O", "Cu2(OH)2CO3", "Cu(NO3)2", "Cu", "CsOH",
         "Cs", "CrCl3", "Cr2O3", "Cr2(SO4)3", "Cr", "CoSO4", "CoS", "CoCl2", "Co3O4", "Co2O3", "Co(NO3)2", "Co", "Cl2",
         "Cl", "CeO2", "Ce(SO4)2", "Ce", "CdS", "CdCl2", "CdCO3", "Cd", "CaSO4", "CaO", "CaCl2", "CaCO3", "CaC2O4",
         "Ca3(PO4)2", "Ca(OH)2", "Ca", "CS(NH2)2", "CO2", "CO(NH2)2", "CO", "CH3COONH4", "CH3COOH", "C6H5SO3H",
         "C6H5ONa", "C6H5OH", "C6H5NO2", "C6H5Cl", "C6H5COOH", "C6H5Br", "C6H12", "C", "Br2", "Br", "BiONO3", "BiOHCO3",
         "BiOCl", "BiCl3", "Bi2S3", "Bi2O3", "Bi(NO3)3", "Bi", "BeO", "Be", "BaSO4", "BaO", "BaCrO4", "BaCl2", "BaCO3",
         "BaBr2", "Ba3(AsO4)2", "Ba(OH)2", "Ba", "B2O3", "B", "As2S3", "As2O5", "As2O3", "As", "AlCl3", "AlBr3",
         "Al2O3", "Al2(SO4)3", "Al(OH)3", "Al(NO3)3", "Al", "AgSCN", "AgNO3", "AgI", "AgCl", "AgCN", "AgBrO3", "AgBr",
         "Ag3AsO4", "Ag2SO4", "Ag2CrO4", "Ag", "(NH4)3PO4", "(NH4)2SO4", "(NH4)2S", "(NH4)2PtCl6", "(NH4)2MoO4",
         "(NH4)2HPO4", "(NH4)2Fe(SO4)2", "(NH4)2CO3", "(NH4)2C2O4", "(CH3COO)2UO2", "(CH3COO)2Pb", "(CH3CO)2O",
         "(CH2COO)2Zn"};
const unordered_map<string, vector<string>> valenceData = {
        {"CCl4",           vector<string>({"4 / 1", "-1 / 1"})},
        {"CH3Cl",          vector<string>({"-2 / 1", "-1 / 1", "1 / 1"})},
        {"C2H5OC2H5",      vector<string>({"-2 / 1", "1 / 1", "-2 / 1"})},
        {"KO2",            vector<string>({"1 / 1", "-1 / 2"})},
        {"CuCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"CHCl3",          vector<string>({"2 / 1", "-1 / 1", "1 / 1"})},
        {"CH3Cl",          vector<string>({"-2 / 1", "-1 / 1", "1 / 1"})},
        {"CH3COONa",       vector<string>({"0 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"CH3COOCH3",      vector<string>({"-2 / 3", "1 / 1", "-2 / 1"})},
        {"CH3COOC2H5",     vector<string>({"-1 / 1", "1 / 1", "-2 / 1"})},
        {"CH3CH2Br",       vector<string>({"-1 / 1", "-2 / 1", "1 / 1"})},
        {"CH2Cl2",         vector<string>({"0 / 1", "-1 / 1", "1 / 1"})},
        {"C2H5ONa",        vector<string>({"-2 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"(C2H5O)2Mg",     vector<string>({"-2 / 1", "1 / 1", "2 / 1", "-2 / 1"})},
        {"C2H5ONO2",       vector<string>({"-2 / 1", "1 / 1", "5 / 1", "-2 / 1"})},
        {"CH3CH2OSO3H",    vector<string>({"-2 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"(C2H5O)3Al",     vector<string>({"3 / 1", "-2 / 1", "1 / 1", "-2 / 1"})},
        {"CH3CH2OH",       vector<string>({"-2 / 1", "1 / 1", "-2 / 1"})},
        {"C11H22O11",      vector<string>({"0 / 1", "1 / 1", "-2 / 1"})},
        {"Ba(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"Al2S3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"NaAlO2",         vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"NH3·H2O",        vector<string>({"1 / 1", "-3 / 1", "-2 / 1"})},
        {"AgOH",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"Ca(ClO)2",       vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"Ca(H2PO4)2",     vector<string>({"2 / 1", "1 / 1", "-2 / 1", "5 / 1"})},
        {"CH4",            vector<string>({"-4 / 1", "1 / 1"})},
        {"C2H6",           vector<string>({"-3 / 1", "1 / 1"})},
        {"C2H4",           vector<string>({"-2 / 1", "1 / 1"})},
        {"C2H2",           vector<string>({"-1 / 1", "1 / 1"})},
        {"Fe(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"CaC2",           vector<string>({"-1 / 1", "2 / 1"})},
        {"CH3CHO",         vector<string>({"-1 / 1", "1 / 1", "-2 / 1"})},
        {"C2H5OH",         vector<string>({"-2 / 1", "1 / 1", "-2 / 1"})},
        {"Fe(OH)2",        vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"Ca(HCO3)2",      vector<string>({"4 / 1", "2 / 1", "1 / 1", "-2 / 1"})},
        {"CH3OH",          vector<string>({"-2 / 1", "1 / 1", "-2 / 1"})},
        {"Ag(NH3)2OH",     vector<string>({"1 / 1", "1 / 1", "-3 / 1", "-2 / 1"})},
        {"HCHO",           vector<string>({"0 / 1", "1 / 1", "-2 / 1"})},
        {"HClO",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"MgH2",           vector<string>({"-1 / 1", "2 / 1"})},
        {"K2MnO4",         vector<string>({"1 / 1", "6 / 1", "-2 / 1"})},
        {"KH",             vector<string>({"-1 / 1", "1 / 1"})},
        {"LiH",            vector<string>({"-1 / 1", "1 / 1"})},
        {"NaH",            vector<string>({"-1 / 1", "1 / 1"})},
        {"Cs",             vector<string>({"0 / 1"})},
        {"CsOH",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"KF",             vector<string>({"-1 / 1", "1 / 1"})},
        {"Mg(HCO3)2",      vector<string>({"4 / 1", "1 / 1", "2 / 1", "-2 / 1"})},
        {"Mg3N2",          vector<string>({"2 / 1", "-3 / 1"})},
        {"MgSiO3",         vector<string>({"2 / 1", "-2 / 1", "4 / 1"})},
        {"N2O4",           vector<string>({"4 / 1", "-2 / 1"})},
        {"NO",             vector<string>({"2 / 1", "-2 / 1"})},
        {"NO2",            vector<string>({"4 / 1", "-2 / 1"})},
        {"Na2SO4",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"Cu(OH)2",        vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"H4SiO4",         vector<string>({"1 / 1", "-2 / 1", "4 / 1"})},
        {"H2SiO3",         vector<string>({"1 / 1", "-2 / 1", "4 / 1"})},
        {"NaBr",           vector<string>({"-1 / 1", "1 / 1"})},
        {"NaHS",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"NaHSO3",         vector<string>({"1 / 1", "1 / 1", "-2 / 1", "4 / 1"})},
        {"NaHSO4",         vector<string>({"1 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"Cu3P",           vector<string>({"1 / 1", "-3 / 1"})},
        {"HPO3",           vector<string>({"1 / 1", "-2 / 1", "5 / 1"})},
        {"PCl5",           vector<string>({"-1 / 1", "5 / 1"})},
        {"PCl3",           vector<string>({"-1 / 1", "3 / 1"})},
        {"C6H5SO3H",       vector<string>({"-2 / 3", "1 / 1", "-2 / 1", "4 / 1"})},
        {"C6H12",          vector<string>({"-2 / 1", "1 / 1"})},
        {"C6H5NO2",        vector<string>({"-2 / 3", "1 / 1", "3 / 1", "-2 / 1"})},
        {"C6H6",           vector<string>({"-1 / 1", "1 / 1"})},
        {"C6H5Br",         vector<string>({"-2 / 3", "-1 / 1", "1 / 1"})},
        {"C6H5Cl",         vector<string>({"-2 / 3", "-1 / 1", "1 / 1"})},
        {"C6H5OH",         vector<string>({"-2 / 3", "1 / 1", "-2 / 1"})},
        {"C6H5ONa",        vector<string>({"-2 / 3", "1 / 1", "1 / 1", "-2 / 1"})},
        {"CS2",            vector<string>({"4 / 1", "-2 / 1"})},
        {"K2S",            vector<string>({"1 / 1", "-2 / 1"})},
        {"Ca(HSO3)2",      vector<string>({"2 / 1", "1 / 1", "-2 / 1", "4 / 1"})},
        {"CaSO3",          vector<string>({"2 / 1", "-2 / 1", "4 / 1"})},
        {"CaSiO3",         vector<string>({"2 / 1", "-2 / 1", "4 / 1"})},
        {"Na2SiO3",        vector<string>({"1 / 1", "-2 / 1", "4 / 1"})},
        {"Ag",             vector<string>({"0 / 1"})},
        {"AgBr",           vector<string>({"1 / 1", "-1 / 1"})},
        {"AgBrO3",         vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"AgCl",           vector<string>({"1 / 1", "-1 / 1"})},
        {"AgI",            vector<string>({"1 / 1", "-1 / 1"})},
        {"AgNO3",          vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"Ag2CrO4",        vector<string>({"1 / 1", "6 / 1", "-2 / 1"})},
        {"Ag2SO4",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"Ag3AsO4",        vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"Al",             vector<string>({"0 / 1"})},
        {"AlBr3",          vector<string>({"3 / 1", "-1 / 1"})},
        {"AlCl3",          vector<string>({"3 / 1", "-1 / 1"})},
        {"Al(NO3)3",       vector<string>({"3 / 1", "5 / 1", "-2 / 1"})},
        {"Al2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Al(OH)3",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Al2(SO4)3",      vector<string>({"3 / 1", "-2 / 1", "6 / 1"})},
        {"As",             vector<string>({"0 / 1"})},
        {"As2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"As2O5",          vector<string>({"5 / 1", "-2 / 1"})},
        {"H3AsO4",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"B",              vector<string>({"0 / 1"})},
        {"B2O3",           vector<string>({"3 / 1", "-2 / 1"})},
        {"Ba",             vector<string>({"0 / 1"})},
        {"BaBr2",          vector<string>({"2 / 1", "-1 / 1"})},
        {"BaCO3",          vector<string>({"2 / 1", "4 / 1", "-2 / 1"})},
        {"BaCl2",          vector<string>({"2 / 1", "-1 / 1"})},
        {"BaCrO4",         vector<string>({"2 / 1", "6 / 1", "-2 / 1"})},
        {"BaO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Ba(OH)2",        vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"BaSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Ba3(AsO4)2",     vector<string>({"5 / 1", "2 / 1", "-2 / 1"})},
        {"Be",             vector<string>({"0 / 1"})},
        {"BeO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Bi",             vector<string>({"0 / 1"})},
        {"Bi2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Br",             vector<string>({"0 / 1"})},
        {"NaBrO3",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"Br2",            vector<string>({"0 / 1"})},
        {"C",              vector<string>({"0 / 1"})},
        {"CH3COOH",        vector<string>({"0 / 1", "1 / 1", "-2 / 1"})},
        {"(CH3CO)2O",      vector<string>({"0 / 1", "1 / 1", "-2 / 1"})},
        {"NaAsO4",         vector<string>({"7 / 1", "1 / 1", "-2 / 1"})},
        {"CO",             vector<string>({"2 / 1", "-2 / 1"})},
        {"CO2",            vector<string>({"4 / 1", "-2 / 1"})},
        {"Na2C2O4",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Ca",             vector<string>({"0 / 1"})},
        {"CaCl2",          vector<string>({"2 / 1", "-1 / 1"})},
        {"CaCO3",          vector<string>({"4 / 1", "2 / 1", "-2 / 1"})},
        {"CaC2O4",         vector<string>({"3 / 1", "2 / 1", "-2 / 1"})},
        {"CaO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Ca(OH)2",        vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"CaSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Ca3(PO4)2",      vector<string>({"2 / 1", "-2 / 1", "5 / 1"})},
        {"Cd",             vector<string>({"0 / 1"})},
        {"Ce",             vector<string>({"0 / 1"})},
        {"CeO2",           vector<string>({"4 / 1", "-2 / 1"})},
        {"Cl2",            vector<string>({"0 / 1"})},
        {"Cl",             vector<string>({"0 / 1"})},
        {"Co",             vector<string>({"0 / 1"})},
        {"Cr",             vector<string>({"0 / 1"})},
        {"Na2CrO4",        vector<string>({"6 / 1", "1 / 1", "-2 / 1"})},
        {"Cr2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Cu",             vector<string>({"0 / 1"})},
        {"CuO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Cu2O",           vector<string>({"1 / 1", "-2 / 1"})},
        {"F",              vector<string>({"0 / 1"})},
        {"F2",             vector<string>({"0 / 1"})},
        {"Fe",             vector<string>({"0 / 1"})},
        {"FeO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Fe(OH)3",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Fe2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Fe3O4",          vector<string>({"8 / 3", "-2 / 1"})},
        {"H",              vector<string>({"0 / 1"})},
        {"HBr",            vector<string>({"-1 / 1", "1 / 1"})},
        {"HCOOH",          vector<string>({"2 / 1", "1 / 1", "-2 / 1"})},
        {"CH3COOH",        vector<string>({"0 / 1", "1 / 1", "-2 / 1"})},
        {"C6H5COOH",       vector<string>({"-2 / 7", "1 / 1", "-2 / 1"})},
        {"HCl",            vector<string>({"-1 / 1", "1 / 1"})},
        {"HClO4",          vector<string>({"7 / 1", "1 / 1", "-2 / 1"})},
        {"HF",             vector<string>({"-1 / 1", "1 / 1"})},
        {"HI",             vector<string>({"1 / 1", "-1 / 1"})},
        {"HIO3",           vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"HNO2",           vector<string>({"1 / 1", "3 / 1", "-2 / 1"})},
        {"H2",             vector<string>({"0 / 1"})},
        {"H2CO3",          vector<string>({"4 / 1", "1 / 1", "-2 / 1"})},
        {"H2C2O4",         vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"H2O",            vector<string>({"1 / 1", "-2 / 1"})},
        {"H2S",            vector<string>({"1 / 1", "-2 / 1"})},
        {"H2SO3",          vector<string>({"1 / 1", "-2 / 1", "4 / 1"})},
        {"H2SO4",          vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"H3AsO3",         vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"H3AsO4",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"H3BO3",          vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"H3PO3",          vector<string>({"1 / 1", "-2 / 1", "3 / 1"})},
        {"H3PO4",          vector<string>({"1 / 1", "-2 / 1", "5 / 1"})},
        {"Hg",             vector<string>({"0 / 1"})},
        {"HgO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"I",              vector<string>({"0 / 1"})},
        {"I2",             vector<string>({"0 / 1"})},
        {"K",              vector<string>({"0 / 1"})},
        {"KAl(SO4)2",      vector<string>({"3 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"KBr",            vector<string>({"-1 / 1", "1 / 1"})},
        {"KBrO3",          vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"KCl",            vector<string>({"-1 / 1", "1 / 1"})},
        {"KClO3",          vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"KClO4",          vector<string>({"7 / 1", "1 / 1", "-2 / 1"})},
        {"KHC2O4",         vector<string>({"3 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"KHC4O6H4",       vector<string>({"3 / 2", "1 / 1", "1 / 1", "-2 / 1"})},
        {"KHC8O4H8",       vector<string>({"1 / -4", "1 / 1", "1 / 1", "-2 / 1"})},
        {"KHSO4",          vector<string>({"1 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"KI",             vector<string>({"-1 / 1", "1 / 1"})},
        {"KIO3",           vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"KMnO4",          vector<string>({"1 / 1", "7 / 1", "-2 / 1"})},
        {"KNO2",           vector<string>({"1 / 1", "3 / 1", "-2 / 1"})},
        {"KNO3",           vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"KNaC4O6H4",      vector<string>({"3 / 2", "1 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"KOH",            vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"K2CO3",          vector<string>({"4 / 1", "1 / 1", "-2 / 1"})},
        {"K2CrO4",         vector<string>({"6 / 1", "1 / 1", "-2 / 1"})},
        {"K2Cr2O7",        vector<string>({"6 / 1", "1 / 1", "-2 / 1"})},
        {"K2SO4",          vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"K2S2O7",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"K3AsO4",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"K3PO4",          vector<string>({"1 / 1", "-2 / 1", "5 / 1"})},
        {"Li",             vector<string>({"0 / 1"})},
        {"LiCl",           vector<string>({"-1 / 1", "1 / 1"})},
        {"LiOH",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"Li2CO3",         vector<string>({"4 / 1", "1 / 1", "-2 / 1"})},
        {"Li2O",           vector<string>({"1 / 1", "-2 / 1"})},
        {"Mg",             vector<string>({"0 / 1"})},
        {"MgCO3",          vector<string>({"4 / 1", "2 / 1", "-2 / 1"})},
        {"MgC2O4",         vector<string>({"3 / 1", "2 / 1", "-2 / 1"})},
        {"MgCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"Mg(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"MgO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"Mg(OH)2",        vector<string>({"1 / 1", "2 / 1", "-2 / 1"})},
        {"MgSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Mg2P2O7",        vector<string>({"2 / 1", "-2 / 1", "5 / 1"})},
        {"Mn",             vector<string>({"0 / 1"})},
        {"MnO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"MnO2",           vector<string>({"4 / 1", "-2 / 1"})},
        {"Mn2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Mn3O4",          vector<string>({"8 / 3", "-2 / 1"})},
        {"N",              vector<string>({"0 / 1"})},
        {"N2",             vector<string>({"0 / 1"})},
        {"NH3",            vector<string>({"1 / 1", "-3 / 1"})},
        {"HNO3",           vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"NaNO3",          vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"Na",             vector<string>({"0 / 1"})},
        {"NaBiO3",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"Na",             vector<string>({"0 / 1"})},
        {"NaBrO3",         vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"HCOONa",         vector<string>({"2 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"NaCl",           vector<string>({"-1 / 1", "1 / 1"})},
        {"NaClO",          vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"NaHCO3",         vector<string>({"4 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"NaH2PO4",        vector<string>({"1 / 1", "1 / 1", "-2 / 1", "5 / 1"})},
        {"NaI",            vector<string>({"-1 / 1", "1 / 1"})},
        {"NaNO2",          vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"NaNO3",          vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"NaOH",           vector<string>({"1 / 1", "1 / 1", "-2 / 1"})},
        {"Na2B4O7",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Na2CO3",         vector<string>({"4 / 1", "1 / 1", "-2 / 1"})},
        {"Na2C2O4",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Na2HAsO3",       vector<string>({"3 / 1", "1 / 1", "1 / 1", "-2 / 1"})},
        {"Na2HPO4",        vector<string>({"1 / 1", "1 / 1", "-2 / 1", "5 / 1"})},
        {"Na2O",           vector<string>({"1 / 1", "-2 / 1"})},
        {"Na2S",           vector<string>({"1 / 1", "-2 / 1"})},
        {"Na2SO3",         vector<string>({"1 / 1", "-2 / 1", "4 / 1"})},
        {"Na2SO4",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"Na2S2O3",        vector<string>({"1 / 1", "-2 / 1", "2 / 1"})},
        {"Na3AsO3",        vector<string>({"3 / 1", "1 / 1", "-2 / 1"})},
        {"Na3AsO4",        vector<string>({"5 / 1", "1 / 1", "-2 / 1"})},
        {"Na3PO4",         vector<string>({"1 / 1", "-2 / 1", "5 / 1"})},
        {"Ni",             vector<string>({"0 / 1"})},
        {"NiO",            vector<string>({"2 / 1", "-2 / 1"})},
        {"O",              vector<string>({"0 / 1"})},
        {"H2O",            vector<string>({"1 / 1", "-2 / 1"})},
        {"O2",             vector<string>({"0 / 1"})},
        {"O3",             vector<string>({"0 / 1"})},
        {"P",              vector<string>({"0 / 1"})},
        {"H3PO4",          vector<string>({"1 / 1", "-2 / 1", "5 / 1"})},
        {"P2O5",           vector<string>({"-2 / 1", "5 / 1"})},
        {"Pb",             vector<string>({"0 / 1"})},
        {"PbO",            vector<string>({"-2 / 1", "2 / 1"})},
        {"PbO2",           vector<string>({"-2 / 1", "4 / 1"})},
        {"Pb2O3",          vector<string>({"-2 / 1", "3 / 1"})},
        {"Pb3O4",          vector<string>({"-2 / 1", "8 / 3"})},
        {"S",              vector<string>({"0 / 1"})},
        {"SO2",            vector<string>({"-2 / 1", "4 / 1"})},
        {"SO3",            vector<string>({"-2 / 1", "6 / 1"})},
        {"Na2SO4",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"Sb",             vector<string>({"0 / 1"})},
        {"Sb2O3",          vector<string>({"-2 / 1", "3 / 1"})},
        {"Sb2O5",          vector<string>({"-2 / 1", "5 / 1"})},
        {"Si",             vector<string>({"0 / 1"})},
        {"SiF4",           vector<string>({"-1 / 1", "4 / 1"})},
        {"SiO2",           vector<string>({"-2 / 1", "4 / 1"})},
        {"Sn",             vector<string>({"0 / 1"})},
        {"SnO2",           vector<string>({"-2 / 1", "4 / 1"})},
        {"Sr",             vector<string>({"0 / 1"})},
        {"SrO",            vector<string>({"-2 / 1", "2 / 1"})},
        {"Th",             vector<string>({"0 / 1"})},
        {"Ti",             vector<string>({"0 / 1"})},
        {"TiO2",           vector<string>({"-2 / 1", "4 / 1"})},
        {"U",              vector<string>({"0 / 1"})},
        {"UF4",            vector<string>({"-1 / 1", "4 / 1"})},
        {"UO3",            vector<string>({"-2 / 1", "6 / 1"})},
        {"U3O8",           vector<string>({"-2 / 1", "16 / 3"})},
        {"V",              vector<string>({"0 / 1"})},
        {"VO2",            vector<string>({"-2 / 1", "4 / 1"})},
        {"V2O5",           vector<string>({"-2 / 1", "5 / 1"})},
        {"W",              vector<string>({"0 / 1"})},
        {"WO3",            vector<string>({"-2 / 1", "6 / 1"})},
        {"Zn",             vector<string>({"0 / 1"})},
        {"ZnCO3",          vector<string>({"4 / 1", "-2 / 1", "2 / 1"})},
        {"ZnC2O4",         vector<string>({"3 / 1", "-2 / 1", "2 / 1"})},
        {"(CH2COO)2Zn",    vector<string>({"1 / 2", "1 / 1", "-2 / 1", "2 / 1"})},
        {"ZnCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"Zn(NO3)2",       vector<string>({"5 / 1", "-2 / 1", "2 / 1"})},
        {"ZnO",            vector<string>({"-2 / 1", "2 / 1"})},
        {"ZnS",            vector<string>({"-2 / 1", "2 / 1"})},
        {"ZnSO4",          vector<string>({"-2 / 1", "6 / 1", "2 / 1"})},
        {"Zn2P2O7",        vector<string>({"-2 / 1", "5 / 1", "2 / 1"})},
        {"Zr",             vector<string>({"0 / 1"})},
        {"ZrO2",           vector<string>({"-2 / 1", "4 / 1"})},
        {"KAl(SO4)2",      vector<string>({"3 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"BiCl3",          vector<string>({"3 / 1", "-1 / 1"})},
        {"Bi(NO3)3",       vector<string>({"3 / 1", "5 / 1", "-2 / 1"})},
        {"BiOCl",          vector<string>({"3 / 1", "-1 / 1", "-2 / 1"})},
        {"BiONO3",         vector<string>({"3 / 1", "5 / 1", "-2 / 1"})},
        {"NaCO3",          vector<string>({"4 / 1", "1 / 1", "-2 / 1"})},
        {"CS(NH2)2",       vector<string>({"4 / 1", "1 / 1", "-3 / 1", "-2 / 1"})},
        {"CdS",            vector<string>({"2 / 1", "-2 / 1"})},
        {"CoCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"CdCl2",          vector<string>({"2 / 1", "-1 / 1"})},
        {"Co(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"CoSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Co2O3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"Co3O4",          vector<string>({"8 / 3", "-2 / 1"})},
        {"CrCl3",          vector<string>({"-1 / 1", "3 / 1"})},
        {"CuCl",           vector<string>({"-1 / 1", "1 / 1"})},
        {"CuCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"CuI",            vector<string>({"1 / 1", "-1 / 1"})},
        {"Cu(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"CuSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Cu2S",           vector<string>({"1 / 1", "-2 / 1"})},
        {"FeCO3",          vector<string>({"4 / 1", "2 / 1", "-2 / 1"})},
        {"FeCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"FeCl3",          vector<string>({"-1 / 1", "3 / 1"})},
        {"Fe(NO3)3",       vector<string>({"3 / 1", "5 / 1", "-2 / 1"})},
        {"FeSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Fe2(SO4)3",      vector<string>({"3 / 1", "-2 / 1", "6 / 1"})},
        {"HgCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"HgI2",           vector<string>({"2 / 1", "-1 / 1"})},
        {"Hg(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"HgSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"Hg2Br2",         vector<string>({"-1 / 1", "1 / 1"})},
        {"Hg2Cl2",         vector<string>({"-1 / 1", "1 / 1"})},
        {"Hg2I2",          vector<string>({"1 / 1", "-1 / 1"})},
        {"Hg2(NO3)2",      vector<string>({"1 / 1", "5 / 1", "-2 / 1"})},
        {"Hg2SO4",         vector<string>({"1 / 1", "-2 / 1", "6 / 1"})},
        {"KFe(SO4)2",      vector<string>({"3 / 1", "1 / 1", "-2 / 1", "6 / 1"})},
        {"K3Fe(CN)6",      vector<string>({"2 / 1", "3 / 1", "1 / 1", "-3 / 1"})},
        {"K4Fe(CN)6",      vector<string>({"2 / 1", "2 / 1", "1 / 1", "-3 / 1"})},
        {"MnCO3",          vector<string>({"4 / 1", "2 / 1", "-2 / 1"})},
        {"MnCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"Mn(NO3)2",       vector<string>({"2 / 1", "5 / 1", "-2 / 1"})},
        {"MnSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"NiCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"Ni(NO3)2",       vector<string>({"5 / 1", "2 / 1", "-2 / 1"})},
        {"NiSO4",          vector<string>({"2 / 1", "-2 / 1", "6 / 1"})},
        {"PbCO3",          vector<string>({"4 / 1", "-2 / 1", "2 / 1"})},
        {"PbC2O4",         vector<string>({"3 / 1", "-2 / 1", "2 / 1"})},
        {"PbCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"PbI2",           vector<string>({"-1 / 1", "2 / 1"})},
        {"Pb(NO3)2",       vector<string>({"5 / 1", "-2 / 1", "2 / 1"})},
        {"PbSO4",          vector<string>({"-2 / 1", "2 / 1", "6 / 1"})},
        {"Pb3(PO4)2",      vector<string>({"-2 / 1", "5 / 1", "2 / 1"})},
        {"SbCl3",          vector<string>({"-1 / 1", "3 / 1"})},
        {"SbCl5",          vector<string>({"-1 / 1", "5 / 1"})},
        {"SiCl4",          vector<string>({"-1 / 1", "4 / 1"})},
        {"SnCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"SrCO3",          vector<string>({"4 / 1", "-2 / 1", "2 / 1"})},
        {"SrCl2",          vector<string>({"-1 / 1", "2 / 1"})},
        {"Sr(NO3)2",       vector<string>({"5 / 1", "-2 / 1", "2 / 1"})},
        {"SrSO4",          vector<string>({"-2 / 1", "6 / 1", "2 / 1"})},
        {"Sr3(PO4)2",      vector<string>({"-2 / 1", "5 / 1", "2 / 1"})},
        {"ThCl4",          vector<string>({"-1 / 1", "4 / 1"})},
        {"Th(NO3)4",       vector<string>({"5 / 1", "-2 / 1", "4 / 1"})},
        {"Th(SO4)2",       vector<string>({"-2 / 1", "6 / 1", "4 / 1"})},
        {"TiCl3",          vector<string>({"-1 / 1", "3 / 1"})},
        {"TiCl4",          vector<string>({"-1 / 1", "4 / 1"})},
        {"TiOSO4",         vector<string>({"-2 / 1", "6 / 1", "4 / 1"})},
        {"UCl4",           vector<string>({"-1 / 1", "4 / 1"})},
        {"Zr(NO3)4",       vector<string>({"5 / 1", "-2 / 1", "4 / 1"})},
        {"ZrOCl2",         vector<string>({"-1 / 1", "-2 / 1", "4 / 1"})},
        {"Zr(SO4)2",       vector<string>({"-2 / 1", "6 / 1", "4 / 1"})},
        {"BiOHCO3",        vector<string>({"3 / 1", "4 / 1", "1 / 1", "-2 / 1"})},
        {"CdCO3",          vector<string>({"4 / 1", "2 / 1", "-2 / 1"})},
        {"Ce(SO4)2",       vector<string>({"4 / 1", "-2 / 1", "6 / 1"})},
        {"Cr2(SO4)3",      vector<string>({"3 / 1", "-2 / 1", "6 / 1"})},
        {"Cu2(OH)2CO3",    vector<string>({"4 / 1", "2 / 1", "1 / 1", "-2 / 1"})},
        {"Mn2P2O7",        vector<string>({"2 / 1", "-2 / 1", "5 / 1"})},
        {"PbCrO4",         vector<string>({"6 / 1", "-2 / 1", "2 / 1"})},
        {"AgCN",           vector<string>({"1 / 1", "2 / 1", "-3 / 1"})},
        {"AgSCN",          vector<string>({"1 / 1", "4 / 1", "-3 / 1", "-2 / 1"})},
        {"Bi2S3",          vector<string>({"3 / 1", "-2 / 1"})},
        {"HCN",            vector<string>({"2 / 1", "1 / 1", "-3 / 1"})},
        {"NaCN",           vector<string>({"2 / 1", "-3 / 1", "1 / 1"})},
        {"CO(NH2)2",       vector<string>({"4 / 1", "1 / 1", "-3 / 1", "-2 / 1"})},
        {"CoS",            vector<string>({"2 / 1", "-2 / 1"})},
        {"CuS",            vector<string>({"2 / 1", "-2 / 1"})},
        {"(NH4)2Fe(SO4)2", vector<string>({"2 / 1", "1 / 1", "-3 / 1", "-2 / 1", "6 / 1"})}
};
using State = cocr::ChemistryData::State;
const unordered_map<string, State> stateData = {
        {"ZnSO4",       State::soluble},
        {"ZnCl2",       State::soluble},
        {"Zn(NO3)2",    State::soluble},
        {"Zn",          State::metal},
        {"WO3",         State::solid},
        {"W",           State::metal},
        {"V2O5",        State::solid},
        {"V",           State::metal},
        {"SiO2",        State::solid},
        {"SiF4",        State::gass},
        {"Si",          State::solid},
        {"SO3",         State::liquid},
        {"SO2",         State::gass},
        {"S",           State::solid},
        {"PhSO3H",      State::organic},
        {"PhONa",       State::soluble},
        {"PhOH",        State::solid},
        {"PhNO2",       State::organic},
        {"PhCl",        State::organic},
        {"PhBr",        State::organic},
        {"Ph",          State::organic},
        {"PbS",         State::solid},
        {"PbAc2",       State::soluble},
        {"PCl5",        State::solid},
        {"PCl3",        State::solid},
        {"P2O5",        State::solid},
        {"P",           State::solid},
        {"O2",          State::gass},
        {"NaSO4",       State::soluble},
        {"NaOH",        State::soluble},
        {"NaNO3",       State::soluble},
        {"NaNO2",       State::soluble},
        {"NaHSO4",      State::soluble},
        {"NaHSO3",      State::soluble},
        {"NaHS",        State::soluble},
        {"NaHCO3",      State::soluble},
        {"NaClO",       State::soluble},
        {"NaCl",        State::soluble},
        {"NaBr",        State::soluble},
        {"NaAlO2",      State::soluble},
        {"Na2SiO3",     State::soluble},
        {"Na2SO4",      State::soluble},
        {"Na2SO3",      State::soluble},
        {"Na2S",        State::soluble},
        {"Na2O2",       State::solid},
        {"Na2O",        State::solid},
        {"Na2CO3",      State::soluble},
        {"Na",          State::metal},
        {"NO2",         State::gass},
        {"NO",          State::gass},
        {"NH4NO3",      State::soluble},
        {"NH4HCO3",     State::soluble},
        {"NH4Cl",       State::soluble},
        {"NH3·H2O",     State::liquid},
        {"NH3",         State::gass},
        {"N2O4",        State::gass},
        {"N2",          State::gass},
        {"MnSO4",       State::soluble},
        {"MnO2",        State::solid},
        {"MnO",         State::solid},
        {"MnCl2",       State::soluble},
        {"Mn",          State::metal},
        {"MgSiO3",      State::solid},
        {"MgSO4",       State::soluble},
        {"MgO",         State::solid},
        {"MgCl2",       State::soluble},
        {"MgCO3",       State::solid},
        {"Mg3N2",       State::solid},
        {"Mg(OH)2",     State::solid},
        {"Mg(NO3)2",    State::soluble},
        {"Mg(HCO3)2",   State::soluble},
        {"Mg",          State::metal},
        {"MX",          State::soluble},
        {"MOH",         State::soluble},
        {"MH",          State::solid},
        {"M",           State::metal},
        {"Li2O",        State::solid},
        {"Li",          State::metal},
        {"KOH",         State::soluble},
        {"KO2",         State::solid},
        {"KNO3",        State::soluble},
        {"KMnO4",       State::soluble},
        {"KI",          State::soluble},
        {"KClO3",       State::soluble},
        {"KCl",         State::soluble},
        {"KBr",         State::soluble},
        {"K2SO4",       State::soluble},
        {"K2S",         State::soluble},
        {"K2MnO4",      State::soluble},
        {"KAl(SO4)2",   State::soluble},
        {"K2Cr2O7",     State::soluble},
        {"K",           State::metal},
        {"I2",          State::solid},
        {"HgO",         State::solid},
        {"Hg(NO3)2",    State::soluble},
        {"Hg",          State::solid},
        {"HPO3",        State::solid},
        {"HNO3",        State::soluble},
        {"HI",          State::soluble},
        {"HF",          State::soluble},
        {"HClO",        State::liquid},
        {"HCl",         State::soluble},
        {"HCIO",        State::liquid},
        {"HCHO",        State::organic},
        {"HBr",         State::soluble},
        {"HAc",         State::liquid},
        {"H4SiO4",      State::solid},
        {"H3PO4",       State::liquid},
        {"H2SiO3",      State::solid},
        {"H2SO4",       State::soluble},
        {"H2SO3",       State::liquid},
        {"H2S",         State::gass},
        {"H2O2",        State::liquid},
        {"H2O",         State::liquid},
        {"H2CO3",       State::liquid},
        {"H2",          State::gass},
        {"FeSO4",       State::soluble},
        {"FeS2",        State::solid},
        {"FeS",         State::solid},
        {"FeO",         State::solid},
        {"FeCl3",       State::liquid},
        {"FeCl2",       State::soluble},
        {"Fe3O4",       State::solid},
        {"Fe2O3",       State::solid},
        {"Fe2(SO4)3",   State::soluble},
        {"FeSO4",       State::soluble},
        {"Fe(OH)3",     State::solid},
        {"Fe(OH)2",     State::solid},
        {"Fe(NO3)2",    State::soluble},
        {"Fe",          State::metal},
        {"F2",          State::gass},
        {"CuSO4",       State::soluble},
        {"CuS",         State::solid},
        {"CuO",         State::solid},
        {"CuCl2",       State::soluble},
        {"Cu3P",        State::solid},
        {"Cu2S",        State::solid},
        {"Cu2O",        State::solid},
        {"Cu(OH)2",     State::solid},
        {"Cu(NO3)2",    State::soluble},
        {"Cu",          State::solid},
        {"Cr2O3",       State::solid},
        {"Cr2(SO4)3",   State::soluble},
        {"Cr",          State::metal},
        {"Cl2",         State::gass},
        {"CaSiO3",      State::solid},
        {"CaSO4",       State::solid},
        {"CaSO3",       State::solid},
        {"CaO",         State::solid},
        {"CaCl2",       State::soluble},
        {"CaCO3",       State::solid},
        {"CaC2",        State::solid},
        {"Ca3(PO4)2",   State::solid},
        {"Ca(OH)2",     State::soluble},
        {"Ca(HSO3)2",   State::soluble},
        {"Ca(HCO3)2",   State::soluble},
        {"Ca(H2PO4)2",  State::soluble},
        {"Ca(ClO)2",    State::soluble},
        {"CS2",         State::liquid},
        {"CO2",         State::gass},
        {"CO",          State::gass},
        {"CHCl3",       State::liquid},
        {"CH4",         State::gass},
        {"CH3OH",       State::liquid},
        {"CH3Cl",       State::gass},
        {"CH3COONa",    State::soluble},
        {"CH3COONH4",   State::soluble},
        {"CH3COOH",     State::liquid},
        {"CH3COOCH3",   State::liquid},
        {"CH3COOC2H5",  State::liquid},
        {"CH3CHO",      State::liquid},
        {"CH3CH2OSO3H", State::organic},
        {"CH3CH2OH",    State::liquid},
        {"CH3CH2Br",    State::organic},
        {"CH2Cl2",      State::organic},
        {"CCl4",        State::liquid},
        {"C6H6",        State::liquid},
        {"C2H6",        State::gass},
        {"C2H5ONa",     State::soluble},
        {"C2H5ONO2",    State::organic},
        {"C2H5OH",      State::liquid},
        {"C2H5OC2H5",   State::organic},
        {"C2H4",        State::gass},
        {"C2H2",        State::gass},
        {"C11H22O11",   State::solid},
        {"C",           State::solid},
        {"Br2",         State::liquid},
        {"BaSO4",       State::solid},
        {"BaCl2",       State::soluble},
        {"BaCO3",       State::solid},
        {"Ba(NO3)2",    State::soluble},
        {"AlCl3",       State::soluble},
        {"Al2S3",       State::solid},
        {"Al2O3",       State::solid},
        {"Al2(SO4)3",   State::soluble},
        {"Al(OH)3",     State::solid},
        {"Al(NO3)3",    State::soluble},
        {"Al",          State::metal},
        {"AgOH",        State::solid},
        {"AgNO3",       State::soluble},
        {"AgI",         State::solid},
        {"AgCl",        State::solid},
        {"AgBr",        State::solid},
        {"Ag(NH3)2OH",  State::soluble},
        {"Ag",          State::solid},
        {"(NH4)2SO4",   State::soluble},
        {"(CH3COO)2Pb", State::soluble},
        {"(C2H5O)3Al",  State::soluble},
        {"(C2H5O)2Mg",  State::soluble}
};


namespace cocr {
    ChemistryData::ChemistryData() :
            mass(massData), electronegativity(electronegativityData), name(nameData), formula(formulaData),
            valence(valenceData), state(stateData) {}

    const vector<float> &ChemistryData::getMass() const {
        return mass;
    }

    const vector<float> &ChemistryData::getElectronegativity() const {
        return electronegativity;
    }

    const vector<string> &ChemistryData::getName() const {
        return name;
    }

    const vector<string> &ChemistryData::getFormula() const {
        return formula;
    }

    const std::unordered_map<std::string, std::vector<std::string>> &ChemistryData::getValence() const {
        return valence;
    }

    const std::unordered_map<std::string, State> &ChemistryData::getState() const {
        return state;
    }

}


