# this file is used to config 3rdparty cmake options
set(NCNN_BUILD_BENCHMARK OFF CACHE INTERNAL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE INTERNAL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE INTERNAL "" FORCE)
set(NCNN_INSTALL_SDK OFF CACHE INTERNAL "" FORCE)
if (WASM)
    set(NCNN_THREADS OFF CACHE INTERNAL "" FORCE) # enable it from PTHREAD
    set(NCNN_SHARED_LIB OFF CACHE INTERNAL "" FORCE)
else ()
    set(NCNN_THREADS ON CACHE INTERNAL "" FORCE)
    set(NCNN_SHARED_LIB ON CACHE INTERNAL "" FORCE)
endif ()