# https://stackoverflow.com/questions/7787823
macro(GET_SUB_DIR_NAME RESULT CURRENT_PATH)
    file(GLOB CHILDREN RELATIVE ${CURRENT_PATH} LIST_DIRECTORIES true ${CURRENT_PATH}/*)
    set(DIR_LIST "")
    foreach (CHILD ${CHILDREN})
        if (IS_DIRECTORY ${CURRENT_PATH}/${CHILD})
            list(APPEND DIR_LIST ${CHILD})
        endif ()
    endforeach ()
    set(${RESULT} ${DIR_LIST})
    unset(DIR_LIST)
    unset(CHILDREN)
endmacro()

macro(GET_ALL_SUB_DIR_NAME RESULT CURRENT_PATH)
    file(GLOB_RECURSE CHILDREN RELATIVE ${CURRENT_PATH} LIST_DIRECTORIES true ${CURRENT_PATH}/*)
    set(DIR_LIST "")
    foreach (CHILD ${CHILDREN})
        if (IS_DIRECTORY ${CURRENT_PATH}/${CHILD})
            list(APPEND DIR_LIST ${CHILD})
        endif ()
    endforeach ()
    set(${RESULT} ${DIR_LIST})
    unset(DIR_LIST)
    unset(CHILDREN)
endmacro()

macro(PATH_2_DIR_NAME RESULT CURRENT_PATH)
    string(REGEX REPLACE "(.*\\/)(.*)(\\/)" "\\2" ${RESULT} "${CURRENT_PATH}")
endmacro()

function(findQtModules)
    GET_SUB_DIR_NAME(QT_MODULE_DIR_LIST ${Qt5_DIR}/../)
    foreach (QT_MODULE ${QT_MODULE_DIR_LIST})
        set(${QT_MODULE}_DIR ${Qt5_DIR}/../${QT_MODULE} CACHE INTERNAL "")
    endforeach ()
endfunction()

function(writeFileIfChanged OUTPUT_PATH OUTPUT_BUFFER)
    if (EXISTS ${OUTPUT_PATH})
        file(READ ${OUTPUT_PATH} OLD_OUTPUT_BUFFER)
        if (NOT "${OUTPUT_BUFFER}" STREQUAL "${OLD_OUTPUT_BUFFER}")
            file(WRITE ${OUTPUT_PATH} "${OUTPUT_BUFFER}")
        endif ()
    else ()
        file(WRITE ${OUTPUT_PATH} "${OUTPUT_BUFFER}")
    endif ()
endfunction()

function(copyQtWasmTemplates TEMPLATE_ROOT APP_NAME OUTPUT_ROOT)
    file(GLOB WASM_TEMPLATES ${TEMPLATE_ROOT})
    add_custom_target(${APP_NAME}_wasm_template)
    add_dependencies(${APP_NAME} ${APP_NAME}_wasm_template)
    foreach (WASM_TEMPLATE ${WASM_TEMPLATES})
        get_filename_component(WASM_TEMPLATE_NAME ${WASM_TEMPLATE} NAME)
        if (${WASM_TEMPLATE_NAME} STREQUAL "index.html") # replace APP_NAME placeholder to real ${APP_NAME}
            file(READ ${WASM_TEMPLATE} OLD_INDEX_HTML_BUFFER)
            string(REPLACE "APP_NAME" "${APP_NAME}" INDEX_HTML_BUFFER "${OLD_INDEX_HTML_BUFFER}")
            writeFileIfChanged(${OUTPUT_ROOT}/${WASM_TEMPLATE_NAME} "${INDEX_HTML_BUFFER}")
        else () # just copy
            add_custom_command(TARGET ${APP_NAME}_wasm_template POST_BUILD COMMAND ${CMAKE_COMMAND} -E
                    copy ${WASM_TEMPLATE} ${OUTPUT_ROOT})
        endif ()
    endforeach ()
endfunction()

function(writeQrcFileBySearchDirectory OUTPUT_PATH SEARCH_DIR RELATIVE_DIR)
    file(GLOB_RECURSE QRC_FILE_LIST RELATIVE ${RELATIVE_DIR} ${SEARCH_DIR}/**)

    set(QRC_BUFFER "<RCC>\n<qresource prefix=\"/\">\n")
    foreach (QRC_FILE ${QRC_FILE_LIST})
        string(APPEND QRC_BUFFER "<file compress=\"9\" compress-algo=\"best\">")
        string(APPEND QRC_BUFFER "${QRC_FILE}")
        string(APPEND QRC_BUFFER "</file>\n")
    endforeach ()
    string(APPEND QRC_BUFFER "</qresource>\n</RCC>")

    writeFileIfChanged(${OUTPUT_PATH} "${QRC_BUFFER}")
endfunction()